name: FastAPI CI Pipeline

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    - name: Run Tests
      run: |
        pytest --asyncio-mode=auto --disable-warnings

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 fastapi-app

    - name: Push Docker Image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag fastapi-app $DOCKER_USERNAME/fastapi-app:latest
        docker push $DOCKER_USERNAME/fastapi-app:latest
